#include<iostream>
#include<vector>
#include<random>
#include<time.h>
using namespace std;
string TakeString(){
    srand(time(0));
    int randam = rand();
    vector<string> st ;/*={"The whole point was to find a way to practice nuclear war without destroying ourselves.","To get the computers to learn from mistakes we couldn't afford to make. Except I never could get Joshua to learn the most important lesson.", "I was long into my second decade of living single before I came to see my friends in the city for what they were: my personal community, my urban tribe." , "Seriously though, in this day and age I don't know why we're still cutting open frogs to see what's inside them. If somebody tells me there's a heart and intestines inside a frog, I'm willing to take their word for it."}*/;
    st.push_back("I sing the body electric, the armies of those I love engirth me and I engirth them, they will not let me off till I go with them, respond to them, and discorrupt them, and charge them full with the charge of the soul.");
    st.push_back("Have you ever experienced a time when no matter how hard you tried, you failed, and the time you spent felt wasted? If ever you feel such pangs of regret, try to remember this tale... the story of a young man's quest to save a sweet princess.");
    st.push_back(" there were an answer I could give you to how the universe works, it wouldn't be special. It would just be machinery fulfilling its cosmic design.");
    st.push_back("It would just be a big, dumb food processor. But since nothing seems to make sense, when you find something or someone that does, it's euphoria.");
    st.push_back("I learned from my parents' mistakes, and your mother learned from hers, just as you'll learn from our mistakes and be better with your children until someone, someday, many years from now, finally has a perfect childhood.");
    st.push_back("Cinderella is escorted to the castle to meet prince Charles, who learns that she is the girl he danced with at the ball; the evil Zaral strikes again.");
    st.push_back("You make me feel like I can do anything and I am so happy to be with you. Thank you for being the wonderful, amazing person that you are. You surprise me every day and you warm my heart every night. I am the person I am today because you've loved me and helped me, love.");

    st.push_back("Listen to me, okay? I'm in love with you. I love you every second of the day. And I’ve never loved anyone as I love you. I cry over you not because I'm in pain but because I feel so blessed that I just can't hide my emotions. You are on my mind every moment. I've never missed anyone as I miss you. You are someone special to me. Please be with me forever and ever.");
    st.push_back("I can only use so many words in the dictionary to show you how much I love you. I love you so much that you are always on my mind, putting a smile on my face and making my heart skip a beat. There are so many ways to express my love, and I plan to show you just how much love I have for you for the rest of my life. I hope that my actions let you know the extent of my affection, adoration, and commitment to you.");
    st.push_back("I want you every second of every day from now until the end of forever. I didn't believe in love, and now I understand that I just spent my time gratuitously. But, being with you has changed my outlook on love and life entirely. I now know true love exists. Because I found it with you. I love you.");
    st.push_back("Before I met you; I didn't think love was for me. It was something other people had and felt. Something in movies and TV shows. It felt more like a wish I had than something real. Now that I'm with you, love is so much more tangible. It's something I can reach out and touch. It's so much more than a wish or a hope (though it does give me hope for so many things); it's the genuine, wonderful person I wake up to—the warm hand next to mine, the brush of hair against my cheek. I love you, and because of that love, I love so much more than you. I love myself and the world in a way I never thought possible. You've made that possible for me. You've made everything possible.");
    st.push_back("With ferocity filled with tenderness, you have captured my soul and every bit of me, making me feel like the only man in the world. Life without you is like living without a backbone system. Your raft of love and kindness has held me afloat and will keep on lighting our path. I promise to never leave you.");
    st.push_back("I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.");
    st.push_back("I love you. That is all I know. I hope that you know that I will always be there for you. It is not just for the good times when we are celebrating and enjoying life, but for the bad times. When you are sad, stressed out, or angry, just know that I will be by your side to see you through the tough times. I will hold your hand and lead you through the storm. And when things are going great, I will be there to cheer you on and dance with you.");
    st.push_back("So just to brag on my amazing girlfriend for a minute! You are so sweet, and I'm so blessed to have such a thoughtful wonderful woman in my life. I love you, honey! I can't wait to start the rest of my life with you!! You mean the absolute world to me, and I'm so happy to have you! Thank you for continuing to make me happy every single day! You're beyond perfect.");
    st.push_back("Everything you do, The way you eat, the way you smile, the way my name rolls off of your tongue. That all is what keeps me going. It gives me so much joy to watch you be you. I would never give my attention to anyone else because I love giving it to you. The day when you were born, it was raining. It wasn't raining itself, but heaven was crying for losing the most beautiful Angel!");
    st.push_back("I want you to know that there's no one who can replace you. The way you look. The way you always know what I am thinking about. The way you hug me when I need it the most. The way you listen to me. It's all priceless. You have touched me more than I ever thought you could. I am head over heels in love with you.");
    st.push_back("You are my tender half of a heart. You are my kindest and most important person on Earth. I feel so good when you're close to me. But there are times when we have to part for a while, and then I'm very lonely without you, my love. I miss you every minute, every second, and look forward to our meeting, my baby. My love will always warm you. You are my magnet, dear. I want to put you into my heart and never let you go.");
    st.push_back("I dream of a new date, choking in anguish. The world is bleak without you. I'm madly and desperately missing your beautiful, tender voice, pretty smile. I'm depressed and crushed. Save me from the unbearable sorrow.");
    st.push_back("I miss you, my dear and beloved lady, so much that sometimes it is difficult to breathe. I want to run to you and fall into your tender embrace, smell your hair, feel your warmth.");
    st.push_back("The night without you means a night without a dream; the day without you means the day without its ending. Breathing without you has lost its ease; words are confused. There are only flowers without smell, melodies without a soul, black and white world. A touch of sadness falls on everything. Fix it all, my love. Make my world colorful again.");
    st.push_back("I love hugging you but I hate letting go. I love saying hello, but I hate saying goodbye. I love watching you come towards me, but I hate watching you walk away. I miss you.");
    st.push_back("I have been diagnosed with the deadly I Miss You Syndrome, due to which I suffer from a permanent and irreversible disability of Missing You all the time. I miss you, sweetheart.");
    st.push_back("When we are together, time just flies away like a jet plane. But when we are apart, I can feel every ticking second of the clock hammering one nail after another straight in my heart. I miss you, girl.");
    st.push_back("A fish without fins, a bird without wings. A crab without claws, a cat without paws. Me without you, you without me. I miss you.");
    st.push_back("Just like how a beautiful day is incomplete without the bright SUN and a picture-perfect night is unfinished without the radiant MOON and shining STARS, I am incomplete without YOU. I miss you.");
    st.push_back("Missing you is not just a habit; it is a deadly addiction. Missing you is not just a compulsion; it is a painful desperation. I miss you, girl.");
    st.push_back("The sun is rising in the sky, but to me, the day doesn't start until you've risen out of bed. You're the only source of light and warmth I need, lighting up my life with your smile and warming me with your mere presence. Now that you've gotten up and read this, my day has indeed started. Thank you!");
    st.push_back("You're my best friend. The person I can tell all my secrets to, the first person I want to talk to when I wake up, and the last person I want to talk to before I drift off to sleep. When something good happens to me, you're the first person I want to tell.");
    st.push_back("When I'm troubled by something or if I get bad news, you're the one I go to for comfort and support. But you're so much more to me than a friend; you're the love of my life. You're my friend, my lover, my comfort, and my strength. I am so lucky to have you. I just wanted you to know how happy I am to have you in my life.");
    st.push_back("The doctor took an x-ray of my heart and almost fainted. He asked me what happened with a scared look on his face. I told him, don't worry, I gave my heart to you. That's why it is missing.");
    st.push_back("Watching you walk across a room is the greatest gift. The way you move is so graceful and effortless. The way you smile makes me feel at peace. Knowing you're walking towards me is a feeling so hard to describe. It's like coming home, a comfort; only the home is coming to me. I will never know such love, such peace, as you. You're my home.");
    st.push_back("I know we'll be together, always and forever; you have loved me alright regardless of my shortcomings; it's incredible getting all the best from you, knowing I don't deserve it, but you keep telling me, God is on our side, your smile brightens up my day. Love you so much, dear.");
    st.push_back("Is it already dark there? It is already dark here. There are a large number of stars in the sky. The sky always amazes me. It seems to be limitless without any boundaries. You have a strange resemblance to this sky. You amaze me just like this beautiful sky, and my feelings for you have no limitations. I am simply unable to put limits or boundaries to my love for you. It keeps on increasing.");
    st.push_back("I want you to know that you are the most essential thing in my life. You're the reason I do everything. When I get up in the morning, I feel so grateful for every second I have with you and have here on Earth. You give my life meaning; you give my days such joy; you are the reason I smile. Thank you for being with me, for joining me on this journey through life. Your love is everything to me.");
    st.push_back("When you came into my life, I left all my past behind me. I just love this newly found love that makes me feel like a baby again, my sugar I adore you so much.");
    st.push_back("I must be the luckiest man in the world to have such a special person for their love. When I am next to you, I am always pinching myself to confirm that what I see is real. You are everything that I ever needed in this life, and I cannot imagine life without you. I love you, darling.");
    st.push_back("A day that is void of your voice is to mean an incomplete one. For with your voice comes the soul melting laughter, which is all I need to have a great and happy day. I hope mine makes you feel the same way. ");
    // st.push_back("");
    // st.push_back("");
    int size = st.size();
    return st[(randam%size)];

}

int main2()
{
    
return 0;
}